# Generated by Django 3.1.5 on 2021-02-01 04:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CURRENT', 'Current'), ('PERMANENT', 'Permanent')], max_length=10, unique=True)),
                ('address_1', models.CharField(max_length=300)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('BROTHER', 'Brother'), ('Sister', 'Sister'), ('GUARDIAN', 'Guardian')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ELEMENTARY', 'Elementary'), ('SECONDARY', 'Secondary')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('citizenship', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], max_length=10)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
