# Generated by Django 3.1.5 on 2021-02-01 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='student',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='student_management.student'),
        ),
        migrations.AddField(
            model_name='dependents',
            name='student',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='student_management.student'),
        ),
        migrations.AddField(
            model_name='education',
            name='student',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='student_management.student'),
        ),
    ]
